#!/bin/bash

CFGS="\
firsttouch_all_exclusive_device_0,\
offline_pebs_guided_percent_128_small_knapsack_5,\
offline_pebs_guided_percent_128_small_knapsack_10,\
offline_pebs_guided_percent_128_small_knapsack_15,\
offline_pebs_guided_percent_128_small_knapsack_20,\
offline_pebs_guided_percent_128_small_knapsack_25,\
offline_pebs_guided_percent_128_small_knapsack_30,\
offline_pebs_guided_percent_128_small_knapsack_35,\
offline_pebs_guided_percent_128_small_knapsack_40,\
offline_pebs_guided_percent_128_small_knapsack_45,\
offline_pebs_guided_percent_128_small_knapsack_50,\
firsttouch_all_exclusive_device_1"
echo "$CFGS"
